import { AISearchResponse } from '@/types/music';

export const placeholders: string[] = [
  '자동차를 타고 즐겁게 드라이브 하는 장면에 어울리는 음악',
  '예술 작품을 만드는 과정을 담은 영상에 어울리는 음악',
  '게임 하이라이트에 어울리는 음악',
  '여름철 해변에서 서핑이나 수상 스포츠를 즐기는 영상에 어울리는 음악',
  '도시의 야경을 배경으로 한 루프탑 파티의 분위기에 어울리는 음악',
];

export const QUERIES = {
  AUDIO: {
    KEY: 'audio',
  },
  AI: {
    SEARCH_KEY: 'ai-search',
  },
};

export const searchData: AISearchResponse = {
  musicList: [
    {
      id: '1357489140',
      title: '도둑질',
      category: ['10'],
      artist: '김권환',
      price: '9900',
      genres: [
        'Ambient',
        'Dance',
        'Easy Listening',
        'Electronic',
        'House/Lounge',
        'Industrial',
        'House/Lounge',
        'New Age',
        'Pop',
      ],
      vocals: '연주 곡',
      moods: ['리듬', '모던', '몽환', '신비'],
      instruments: [
        '아날로그 신스',
        '디지털 신스',
        '일렉 기타',
        '전자 오르간',
        '전자 피아노',
        '일렉 베이스',
        '퍼커션',
        '스트링',
        '신스 베이스',
      ],
      key: 'D',
      bpm: '131',
      duration: '181',
      maker: {
        mail: 'gajagajakim@nate.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/1846275068_3364e28a_P20121022_123119000_6C21A37F-0ED8-49DA-AA43-A085C08C846C.JPG',
      },
    },
    {
      id: '1570691647',
      title: 'Smooth Talk - Full Version',
      category: ['10'],
      artist: 'Denis Woods',
      price: '27500',
      genres: ['Ambient', 'Chill-Out', 'Electronic'],
      vocals: '연주 곡',
      moods: ['모던', '몽환', '설레임', '편안함'],
      instruments: ['일렉 기타', '베이스', '피아노', '신스', '드럼셋'],
      key: 'A',
      bpm: '86',
      duration: '122',
      maker: {
        mail: 'PIR13@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/32614788_47e05c02_Denis_Woods.jpg',
      },
    },
    {
      id: '1646639769',
      title: 'Orions Belt - 60sec',
      category: ['10'],
      artist: 'Joel Loopez',
      price: '27500',
      genres: ['Chill-Out', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['도시', '리듬', '모던', '몽환'],
      instruments: ['베이스', '신스', '드럼셋'],
      key: 'C',
      bpm: '85',
      duration: '60',
      maker: {
        mail: 'PIR176@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/2041180796_140ec9df_avatars-GraJDlYeKhgNvBht-3rnZYw-t500x500.jpg',
      },
    },
    {
      id: '1646639770',
      title: 'Orions Belt - Short Loop 5',
      category: ['10'],
      artist: 'Joel Loopez',
      price: '27500',
      genres: ['Chill-Out', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['도시', '리듬', '모던', '몽환'],
      instruments: ['베이스', '신스', '드럼셋'],
      key: 'C',
      bpm: '85',
      duration: '23',
      maker: {
        mail: 'PIR176@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/2041180796_140ec9df_avatars-GraJDlYeKhgNvBht-3rnZYw-t500x500.jpg',
      },
    },
    {
      id: '1646639771',
      title: 'Orions Belt - Short Loop 6',
      category: ['10'],
      artist: 'Joel Loopez',
      price: '27500',
      genres: ['Chill-Out', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['도시', '리듬', '모던', '몽환'],
      instruments: ['베이스', '신스', '드럼셋'],
      key: 'C',
      bpm: '85',
      duration: '23',
      maker: {
        mail: 'PIR176@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/2041180796_140ec9df_avatars-GraJDlYeKhgNvBht-3rnZYw-t500x500.jpg',
      },
    },
    {
      id: '1646640022',
      title: 'Orions Belt - Full Loop',
      category: ['10'],
      artist: 'Joel Loopez',
      price: '27500',
      genres: ['Chill-Out', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['도시', '리듬', '모던', '몽환'],
      instruments: ['베이스', '신스', '드럼셋'],
      key: 'C',
      bpm: '85',
      duration: '150',
      maker: {
        mail: 'PIR176@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/2041180796_140ec9df_avatars-GraJDlYeKhgNvBht-3rnZYw-t500x500.jpg',
      },
    },
    {
      id: '1646640024',
      title: 'Orions Belt - Full Version',
      category: ['10', '4066'],
      artist: 'Joel Loopez',
      price: '27500',
      genres: ['Chill-Out', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['도시', '리듬', '모던', '몽환'],
      instruments: ['베이스', '신스', '드럼셋'],
      key: 'C',
      bpm: '170',
      duration: '167',
      maker: {
        mail: 'PIR176@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/2041180796_140ec9df_avatars-GraJDlYeKhgNvBht-3rnZYw-t500x500.jpg',
      },
    },
    {
      id: '1354798175',
      title: '엉덩이 큰 아가씨',
      category: ['10'],
      artist: '정명훈',
      price: '99000',
      genres: [
        'Classical',
        'Country/Folk',
        'Dance',
        'Electric',
        'Country/Folk',
        'Avant Garde',
        'Hip Hop',
        'Industrial',
        'Jazz',
        'Jazz',
        'Classical',
        'Pop',
        'Rap',
        'Rock',
      ],
      vocals: '남자 보컬 곡',
      moods: [
        '강렬',
        '격렬',
        '경건',
        '경쾌',
        '놀람',
        '달콤',
        '도시',
        '로멘스',
        '리듬',
        '모던',
        '발랄',
        '사랑',
        '설레임',
        '신비',
        '아름다움',
        '장난',
        '평화',
        '환희',
      ],
      instruments: [
        '어커스틱 기타',
        '벨',
        '디지털 신스',
        '일렉 기타',
        '전자 피아노',
        '일렉 베이스',
        '하모니카',
        '피아노',
        '퍼커션',
        '스트링',
        '실로폰',
      ],
      key: 'D',
      bpm: '120',
      duration: '240',
      maker: {
        mail: 'jpion82@naver.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/32614516_29aacff3_jpion.jpg',
      },
    },
    {
      id: '1570697076',
      title: 'Overview - Full Version',
      category: ['10'],
      artist: 'Denis Woods',
      price: '27500',
      genres: ['Dance', 'Electronic', 'Pop'],
      vocals: '연주 곡',
      moods: ['경쾌', '도시', '모던'],
      instruments: ['베이스', '신스', '드럼셋', '퍼커션'],
      key: 'A',
      bpm: '64',
      duration: '128',
      maker: {
        mail: 'PIR13@PartnersInRhyme.com',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/32614788_47e05c02_Denis_Woods.jpg',
      },
    },
    {
      id: '1361101145',
      title: '좀비 21-1',
      category: ['10'],
      artist: '빨간양',
      price: '69300',
      genres: [
        'Easy Listening',
        'Electronic',
        'House/Lounge',
        'Jazz',
        'New Age',
        'Oriental',
        'Rhythm & Blues',
        'Jazz',
        'Techno',
        'Trance',
      ],
      vocals: '연주 곡',
      moods: [
        '격렬',
        '경쾌',
        '긴장',
        '도시',
        '로멘스',
        '리듬',
        '모던',
        '몽환',
        '발랄',
        '설레임',
        '신비',
        '엄숙',
        '편안함',
      ],
      instruments: [
        '디지털 신스',
        '전자 피아노',
        '퍼커션',
        '신스 베이스',
        '트럼펫',
      ],
      key: 'C',
      bpm: '180',
      duration: '95',
      maker: {
        mail: 'huniflute@hanmail.net',
        image:
          'https://www.musicplug.co.kr/index/data/m_photo/32614516_115fc8c2_EBB9A8EAB084EC9691.jpg',
      },
    },
  ],
  tags: {
    genres: [
      {
        value: 'Electronic',
        weight: 85,
      },
      {
        value: 'Ambient',
        weight: 75,
      },
      {
        value: 'Chill-Out',
        weight: 70,
      },
      {
        value: 'Dance',
        weight: 60,
      },
      {
        value: 'Pop',
        weight: 55,
      },
    ],
    moods: [
      {
        value: '몽환',
        weight: 80,
      },
      {
        value: '편안함',
        weight: 75,
      },
      {
        value: '도시',
        weight: 70,
      },
      {
        value: '신비',
        weight: 65,
      },
      {
        value: '모던',
        weight: 60,
      },
    ],
    instruments: [
      {
        value: '실로폰',
        weight: 75,
      },
      {
        value: '신스',
        weight: 70,
      },
      {
        value: '드럼셋',
        weight: 65,
      },
      {
        value: '퍼커션',
        weight: 60,
      },
      {
        value: '베이스',
        weight: 55,
      },
    ],
    vocals: [],
    keys: [
      {
        value: 'C',
        weight: 80,
      },
      {
        value: 'D',
        weight: 75,
      },
      {
        value: 'G',
        weight: 70,
      },
      {
        value: 'A',
        weight: 65,
      },
      {
        value: 'F',
        weight: 60,
      },
    ],
    genresList: ['Electronic', 'Ambient', 'Chill-Out', 'Dance', 'Pop'],
    moodsList: ['몽환', '편안함', '도시', '신비', '모던'],
    instrumentsList: ['실로폰', '신스', '드럼셋', '퍼커션', '베이스'],
    keysList: ['C', 'D', 'G', 'A', 'F'],
    vocalsList: [],
  },
};
